#! /bin/bash
cew_mq_host=MLPSG82A.sg.uobnet.com
cew_mq_port=1414
cew_mq_queue_manager=MLPSG82A
cew_mq_ccsid=819
cew_mq_message_expiry=55000

bms_mq_host=MLPSG82A.sg.uobnet.com
bms_mq_port=1414
bms_mq_queue_manager=MLPSG82A
bms_mq_ccsid=819
bms_mq_message_expiry=55000
bms_mq_channel=MLPSG82A.C01.CEWTH

export bms_mq_host bms_mq_port bms_mq_queue_manager bms_mq_ccsid bms_mq_message_expiry bms_mq_channel

cew_mq_channel_put=MLPSG82A.C02.CEWTH
cew_mq_channel_get=MLPSG82A.C03.CEWTH

eai_mq_channel_get=MLPSG82A.C03.CEWTH
mx_fate_response_tx_update_receive_queue=UOB.CEW.PROD.MNDTTHINTERNALQ

cew_mq_concurrent_consumers=5
cew_mq_max_concurrent_consumers=10

cew_mq_failover_host=MLPSG82B.sg.uobnet.com
cew_mq_failover_hostname=MLPSG82B

pis_ccti_mapping_request_timeout=2000

# Required the following  queues for TH
notify_event_send_queue=UOB.CEW.PROD.THALRTNOTIFYINTERNALQ
ans_notify_event_receive_queue=UOB.CEW.PROD.THALRTNOTIFYINTERNALQ
bulk_file_upload_event_send_queue=UOB.CEW.PROD.THPIS2TWSINTERNALQ
pis_bulk_file_upload_initiate_receive_queue=UOB.CEW.PROD.THPIS2TWSINTERNALQ
notify_reject_initiation_send_queue=UOB.CEW.PROD.THPIS2TWSINTERNALQ
pis_ccti_mapping_receive_queue=UOB.CEW.PROD.THIAFTINTERNALQ
pis_ccti_mapping_send_queue=UOB.CEW.PROD.THIAFTINTERNALQ
pis_ccti_mapping_response_queue=UOB.CEW.PROD.THIAFTINTERNALQ
mcrs_notify_user_send_queue=UOB.CEW.PROD.THMCRS2ANSINTERNALQ
mcrs_notify_user_receive_queue=UOB.CEW.PROD.THMCRS2ANSINTERNALQ
in_flight_async_event_send_queue=UOB.CEW.PROD.THAUTHASYNCINTERNALQ
in_flight_async_event_receive_queue=UOB.CEW.PROD.THAUTHASYNCINTERNALQ
offline_report_event_send_queue=UOB.CEW.PROD.THAUTHASYNCINTERNALQ
offline_report_event_receive_queue=UOB.CEW.PROD.THAUTHASYNCINTERNALQ
aqs_mapping_response_queue=UOB.CEW.PROD.THAUDITINTERNALQ
aqs_mapping_send_queue=UOB.CEW.PROD.THAUDITINTERNALQ
fus_mapping_send_queue=UOB.CEW.PROD.THARCHIVALNOTIFYINTERNALQ
fus_mapping_receive_queue=UOB.CEW.PROD.THARCHIVALNOTIFYINTERNALQ

# Not Required the following  queues for TH so added dummy queue name
pis_mandate_initiate_receive_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
pis_mandate_initiate_send_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
pis_mandate_initiate_response_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
msr_outgoing_send_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
pis_direct_debit_initiation_send_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
request_to_pay_initiation_send_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
npp_mandate_outgoing_receive_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
npp_mandate_outgoing_send_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
npp_mandate_outgoing_response_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
npp_mandate_incoming_receive_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
npp_mandate_incoming_send_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
npp_mandate_incoming_response_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
cew_mq_eai_request_queue=UOB.CEW.PROD.MNDTTHINTERNALQ
cew_mq_eai_response_queue=UOB.CEW.PROD.MNDTTHINTERNALQ

export request_to_pay_initiation_send_queue cew_mq_failover_host
export npp_mandate_incoming_response_queue npp_mandate_incoming_send_queue npp_mandate_incoming_receive_queue npp_mandate_outgoing_response_queue npp_mandate_outgoing_send_queue npp_mandate_outgoing_receive_queue notify_reject_initiation_send_queue pis_direct_debit_initiation_send_queue msr_outgoing_send_queue cew_mq_channel_put cew_mq_channel_get cew_mq_concurrent_consumers pis_ccti_mapping_request_timeout cew_mq_message_expiry cew_mq_ccsid cew_mq_failover_hostname cew_mq_eai_request_queue cew_mq_eai_response_queue cew_mq_host cew_mq_port cew_mq_queue_manager eai_mq_channel_get
export cew_mq_max_concurrent_consumers notify_event_send_queue pis_ccti_mapping_receive_queue pis_ccti_mapping_response_queue bulk_file_upload_event_send_queue pis_mandate_initiate_receive_queue pis_mandate_initiate_send_queue pis_mandate_initiate_response_queue pis_bulk_file_upload_initiate_receive_queue ans_notify_event_receive_queue mcrs_notify_user_send_queue mcrs_notify_user_receive_queue in_flight_async_event_send_queue in_flight_async_event_receive_queue offline_report_event_send_queue offline_report_event_receive_queue aqs_mapping_response_queue aqs_mapping_send_queue fus_mapping_send_queue fus_mapping_receive_queue mx_fate_response_tx_update_receive_queue
